Repository Kazenosinobi/Hand-Hunter, pull requests merged in 2025-02, with the labels that each got.

#121 HH-120: Исправляет заползание текста на иконку очистить текст
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: bug

#128 HH-122: Убирает фокус по умолчанию
  .kotlin/sessions/kotlin-compiler-2716770501450678296.salive
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/SearchFiltersFragment.kt
  app/src/main/res/layout/fragment_search_filters.xml
  app/src/main/res/values/styles.xml
Labels: bug

#129 HH-123: Добавляет фон на экран
  app/src/main/res/layout/fragment_search_filters.xml
Labels: bug

#130 HH-125: Устанавливает фон на экран
  app/src/main/res/layout/fragment_location_selection.xml
Labels: bug

#132 HH-131: Изменение хранения данных фильтра на SharedPreferences
  app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/service/FilterStorage.kt
Labels: tech

#133 HH-124: Скрывает иконки переходов в текстИнпут, во время стейта загрузки
  .kotlin/sessions/kotlin-compiler-17327600664171412640.salive
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/ui/WorkplaceSelectionFragment.kt
Labels: bug

#135 HH-75: Получение и отображение списка стран
  .kotlin/sessions/kotlin-compiler-2716770501450678296.salive
  app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/network/api/HHApi.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/network/service/NetworkClient.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/dto/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/dto/LocationMapDataDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/repository/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/repository/LocationRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/service/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/api/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/api/LocationInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/api/LocationRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/interactor/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/interactor/LocationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/model/Country.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/LocationMapUIDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/ui/LocationSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/viewmodel/LocationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/data/service/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/data/service/.gitkeep
Labels: Epic 5

#137 HH-126 Исправляет переходы на экраны "Выбор страны" и "Выбор региона"
  app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/repository/FilterRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/service/FilterStorage.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/repositoryapi/FilterRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/repository/LocationRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/api/LocationInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/api/LocationRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/interactor/LocationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/LocationMapUIDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/ui/LocationSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/viewmodel/LocationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/ui/WorkplaceSelectionFragment.kt
  app/src/main/res/navigation/main_navigation_graph.xml
Labels: bug

#141 HH-138: Реализует поиск по регионам
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/dto/LocationMapDataDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/interactor/LocationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/model/Region.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/ui/LocationSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/viewmodel/LocationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/ui/WorkplaceSelectionFragment.kt
  app/src/main/res/layout/fragment_workplace_selection.xml
Labels: bug

#144 HH-68: Прорабатывает поисковый запрос с фильтрами
  app/src/main/java/ru/practicum/android/diploma/features/search/domain/interactor/VacanciesSearchInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/domain/interactor/VacanciesSearchInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/domain/model/QuerySearch.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
Labels: Epic 4

#171 HH-163: чинит баг - Экран "Поиск вакансий" - не стартует автоматом поиск
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFiltersFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
Labels: bug

#182 HH-155: Исправляет баги с иконкой фильтра
  .kotlin/sessions/kotlin-compiler-1991691806057835188.salive
  .kotlin/sessions/kotlin-compiler-5164544545868305295.salive
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/MapDomainUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/ui/FilterUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFilterViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFiltersFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
Labels: bug

#183 HH-177: Исправляет баги на экране место работы
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/location/LocationInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/workplace/SelectWorkplaceInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/LocationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/SelectWorkplaceInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/workplace/WorkplaceSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/workplace/WorkplaceSelectionViewModel.kt
Labels: bug

#173 HH-160: Убирает супер фокус у editText
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/SpecializationSelectionFragment.kt
Labels: bug

#188 HH-145: Заменяет пустые строки на null в SharedPrefs
  .kotlin/sessions/kotlin-compiler-1151723951666867353.salive
  .kotlin/sessions/kotlin-compiler-5924985617148585633.salive
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterCountryEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterIndustryEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterMainDataEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterMapperDataDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterRegionEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FullLocationDataEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/repository/FilterRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/service/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/service/FilterStorage.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/filter/FilterInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/filter/FilterRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/location/LocationInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/workplace/SelectWorkplaceInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/FilterInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/LocationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/SelectWorkplaceInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/Country.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/FilterMainData.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/FilterRegion.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/FullLocationData.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/Industry.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/MapDomainUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/api/Regionable.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/ui/CountryUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/ui/FilterUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/ui/IndustryUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/ui/RegionUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/ui/WorkplaceLocationUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFilterViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFiltersFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/SpecializationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/workplace/WorkplaceSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/workplace/WorkplaceSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/domain/interactor/VacanciesSearchInteractorImpl.kt
Labels: bug

#192 HH-191: Убирает повторный поиск
  .kotlin/sessions/kotlin-compiler-11274292707909532032.salive
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/ui/VacancyInfoFragment.kt
Labels: bug

#189 HH-165: Оставляет одну вью модель для регионов
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterMapperDataDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/repository/FilterRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/filter/FilterRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/location/LocationInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/workplace/SelectWorkplaceInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/LocationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/SelectWorkplaceInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/FilterMainData.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/FilterRegion.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/FullLocationData.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/model/Region.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/MapDomainUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionViewModel.kt
Labels: tech

#190 HH-161: Экран "Выбор отрасли" - не сохраняет своё состояние
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterIndustryEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterMapperDataDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/repository/FilterRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/service/FilterStorage.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/filter/FilterRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/specialization/SpecializationInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/SpecializationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/SpecializationSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/SpecializationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/adapter/SpecializationSelectionAdapter.kt
Labels: bug

#185 HH-153: Исправить баг с отображением кнопки "Применить" при изменении…
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/repository/FilterRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/service/FilterStorage.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/filter/FilterInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/filter/FilterRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/FilterInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/MapDomainUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/state/SearchFilterState.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/ui/FilterUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFilterViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFiltersFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
Labels: bug

#195 HH-193: Решает баг с сохранением данных фильтра при выгрузке приложения из памяти
  app/src/main/java/ru/practicum/android/diploma/di/UtilsModule.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/dto/FilterMapperDataDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/repository/FilterRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/data/service/FilterStorage.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/filter/FilterInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/filter/FilterRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/location/LocationInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/specialization/SpecializationInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/workplace/SelectWorkplaceInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/FilterInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/LocationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/SelectWorkplaceInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/SpecializationInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/manager/FilterManager.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/manager/LocationManager.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/domain/manager/SpecializationManager.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/MapDomainUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFilterViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFiltersFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/SpecializationSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/SpecializationSelectionViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/workplace/WorkplaceSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/workplace/WorkplaceSelectionViewModel.kt
Labels: bug

#200 HH-199: Исправляет цвет hint у полей место работы и отрасль на экране фильтров
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFiltersFragment.kt
Labels: bug

#201 HH-197: Исправляет поле ввода
  .kotlin/sessions/kotlin-compiler-8842988215497809438.salive
  app/src/main/res/layout/fragment_search_filters.xml
  app/src/main/res/values/styles.xml
Labels: bug

#207 HH-206: "Выбор отрасли" - баг поиска при отсутствии интернета
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/SpecializationSelectionViewModel.kt
Labels: bug

#210 HH-209: "Выбор региона" - баг поиска при отсутствии интернета
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionViewModel.kt
Labels: bug

#196 HH-168: добавляет кнопку для очистки всего избранного
  app/src/main/java/ru/practicum/android/diploma/features/common/data/database/FavouritesDao.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/data/repository/FavouriteVacanciesRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/api/FavouriteVacanciesInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/api/FavouriteVacanciesRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/interactor/FavouriteVacanciesInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/model/FavouriteVacanciesState.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/ui/FavouriteVacanciesFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/viewmodel/FavouriteVacanciesViewModel.kt
  app/src/main/res/layout/fragment_favourite_vacancies.xml
  app/src/main/res/layout/fragment_location_selection.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
