Repository Kazenosinobi/Hand-Hunter, pull requests merged in 2025-01, with the labels that each got.

#32 HH-31: удаляет .idea из репозитория
  .gitignore
  .idea/.name
  .idea/deploymentTargetSelector.xml
  .idea/migrations.xml
  .idea/vcs.xml
Labels: Epic 0

#41 HH-39: Изменяет нейминг для текста
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: Epic 0

#38 HH-35: реализует верстку экрана Избранное
  .kotlin/sessions/kotlin-compiler-4679570858830645194.salive
  app/src/main/java/ru/practicum/android/diploma/features/root/RootActivity.kt
  app/src/main/res/layout/fragment_favourite_vacancies.xml
  app/src/main/res/layout/fragment_team_info.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Epic 3

#81 HH-30: Реализовывает логику отображения экрана Изобранного
  app/src/main/java/ru/practicum/android/diploma/features/common/data/database/FavouritesDao.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/database/VacancyDbEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/presentation/models/VacancySearchUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/presentation/recycler/VacancyAdapter.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/presentation/recycler/VacancyDiffCallback.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/presentation/recycler/VacancyViewHolder.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/data/dto/VacancyDetailsDbMapper.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/data/repository/FavouriteVacanciesRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/api/FavouriteVacanciesInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/api/FavouriteVacanciesRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/interactor/FavouriteVacanciesInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/model/FavouriteVacanciesState.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/model/FavouriteVacancyUIMapper.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/ui/FavouriteVacanciesFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/viewmodel/FavouriteVacanciesViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/model/VacanciesSearchUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/model/VacancySearchUIMapper.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/data/repository/VacancyDetailsRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/api/VacancyDetailsInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/api/VacancyDetailsRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/interactor/VacancyDetailsInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/ui/VacancyInfoFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/viewmodel/VacancyInfoViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/utils/Formater.kt
  app/src/main/res/layout/fragment_favourite_vacancies.xml
  app/src/main/res/navigation/main_navigation_graph.xml
Labels: Epic 3

#92 HH-90: Исправляет двойной поиск
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
Labels: bug

#88 HH-60: Добавляет признак isFavourite, если вакансия была добавлена в избранное. Добавляет логику удаления вакансии из избранного
  app/src/main/java/ru/practicum/android/diploma/features/common/data/database/FavouritesDao.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/database/VacancyDbEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/model/VacancyDetails.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/data/dto/VacancyDetailsDbMapper.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/data/repository/FavouriteVacanciesRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/data/service/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/api/FavouriteVacanciesInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/api/FavouriteVacanciesRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/interactor/FavouriteVacanciesInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/model/FavouriteVacancyUIMapper.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/ui/FavouriteVacanciesFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/data/dto/VacancyMapToDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/data/repository/VacancyDetailsRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/api/VacancyDetailsInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/api/VacancyDetailsRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/interactor/VacancyDetailsInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/model/VacancyInfoUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/model/VacancyUIMapper.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/ui/VacancyInfoFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/viewmodel/VacancyInfoViewModel.kt
Labels: Epic 3

#105 HH-102: Исправляет отправку запроса при стейте нет интернета
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
Labels: bug

#109 HH-106 Исправление логики экрана Вакансия
  app/src/main/java/ru/practicum/android/diploma/features/common/data/database/VacancyDbEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/network/dto/vacancy/details/DetailsVacancyEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/model/VacancyDetails.kt
  app/src/main/java/ru/practicum/android/diploma/features/favourite/data/dto/VacancyDetailsDbMapper.kt
  app/src/main/java/ru/practicum/android/diploma/features/team/data/dto/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/team/data/repository/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/team/data/service/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/team/domain/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/team/domain/api/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/team/domain/interactor/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/team/domain/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/team/presentation/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/team/presentation/view_model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/data/dto/VacancyMapToDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/model/VacancyUIMapper.kt
  app/src/main/res/values/strings.xml
Labels: bug

#108 HH-107: добавляет обработку ошибки БД при получение ваканси из БД
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/data/repository/VacancyDetailsRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/api/VacancyDetailsInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/api/VacancyDetailsRepository.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/interactor/VacancyDetailsInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/viewmodel/VacancyInfoViewModel.kt
Labels: bug

#114 HH-86: реализует экран Выбор страны
  app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/CountryUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/LocationSelectionState.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/RegionUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/Regionable.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/recycler/LocationAdapter.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/recycler/LocationDiffCallback.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/recycler/LocationViewHolder.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/ui/LocationSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/view_model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/viewmodel/LocationSelectionViewModel.kt
  app/src/main/res/layout/fragment_location_selection.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_location_selection.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Epic 5

#113 HH-85: Создаёт верстку экрана, Fragment, ViewModel
  .kotlin/sessions/kotlin-compiler-6332260735133503131.salive
  app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/CityUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/CountryUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/Regionable.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/WorkplaceLocation.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/WorkplaceLocationState.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/ui/WorkplaceSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/view_model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/viewmodel/WorkplaceSelectionViewModel.kt
  app/src/main/res/drawable/arrow_forward_24px.xml
  app/src/main/res/drawable/work_place_button.xml
  app/src/main/res/layout/fragment_workplace_selection.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Epic 5

#115 HH-67: Хранение состояния экранов фильтра
  .kotlin/sessions/kotlin-compiler-1693530845538721257.salive
  .kotlin/sessions/kotlin-compiler-2744161886905851718.salive
  .kotlin/sessions/kotlin-compiler-7213648984634691390.salive
  app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/dto/FilterCountryEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/dto/FilterIndustryEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/dto/FilterMainDataEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/dto/FilterMapperDataDomain.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/dto/FilterRegionEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/dto/FullLocationDataEntity.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/repository/FilterRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/service/FilterStorage.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/model/FilterCountry.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/model/FilterIndustry.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/model/FilterMainData.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/model/FilterRegion.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/model/FullLocationData.kt
  app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/repositoryapi/FilterRepository.kt
Labels: Epic 4

#117 HH-87: Реализует экран отрасли
  app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/model/Industries.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/model/IndustriesState.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/model/IndustryUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/ui/SpecializationSelectionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/ui/adapter/SpecializationSelectionAdapter.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/ui/adapter/SpecializationSelectionViewHolder.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/viewmodel/SpecializationSelectionViewModel.kt
  app/src/main/res/drawable/choose_button.xml
  app/src/main/res/layout/fragment_specialization_selection.xml
  app/src/main/res/layout/item_specialization.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Epic 5

#116 HH-65: Фильтр - Вёрстка экрана
  app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/FilterUI.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/SearchFiltersFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/view_model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/viewmodel/SearchFilterViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/ui/WorkplaceSelectionFragment.kt
  app/src/main/res/drawable/bg_salary_frame.xml
  app/src/main/res/layout/fragment_search_filters.xml
  app/src/main/res/navigation/main_navigation_graph.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Epic 4
